# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nabomang
email: nathanb93@hotmail.com
description: "Blog about my interests." # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nabomang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Nabomang
github_username: Nabomang
read_time: true
words_per_minute: 200
search_full_content: true
locale: en-US
date_format: "%B %-d, %Y"
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "UA-151956498-1"
disqus:
  shortname: nabomang
logo: /images/logo.png
# skin: "/assets/css/skins/dark.css"


# Build settings
# theme: minima
# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Site Author
author:
  name: Nathan Boone
  picture: /images/nathan.jpg
  email:
  twitter: Nabomang
  links:
    - title: Twitter
      url: https://twitter.com/Nabomang
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/Nabomang
      icon: fab fa-github-square


# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/Nabomang
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/Nabomang
    icon: fab fa-github-square
  - title: Linkedin
    url: https://www.linkedin.com/in/nathan-boone/
    icon: fab fa-linkedin


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
